---
# CVP 를 거치지 않고 eAPI 로 직접 설정을 밀어 넣습니다.
- name: Deploy DCI MPLS-SR EVPN Lab Configurations via eAPI
  hosts: DCI_SR_FABRIC
  gather_facts: false
  tasks:
    - name: Load configuration from file
      arista.eos.eos_config:
        src: ../sites/dci-sr-evpn/intended/configs/{{ inventory_hostname }}.cfg
